#!/bin/bash

if [ -z "$1" ]
then
    echo "Please enter the path of the video file that you wanto to convert"
fi

if [ -f "$1" ]
then
	OUTPUT="$1_for_davinci.mov"

	echo "converting file $1 to $OUTPUT"

	ffmpeg -i $1 -c:v libxvid -q:v 1 -c:a pcm_s24le $OUTPUT
else
    echo "The file $1 does not exist"
fi

