#!/bin/bash

if [ -z "$1" ]
then
    echo "Please enter the path of the video file that you want to to convert"
fi

if [ -f "$1" ]
then
	OUTPUT="$1_fastmp4.mp4"

	echo "converting file $1 to $OUTPUT"

	ffmpeg -i $1 -c:v h264_videotoolbox -b:v 6000k -an $OUTPUT
else
    echo "The file $1 does not exist"
fi

